--- 
all:
  children:
    production:
      hosts:
        server:
          ansible_host: "64.23.210.235"
          ansible_user: "ubuntu"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_python_interpreter: /usr/bin/python3
